import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavElement from "./components/Nav-Element";
import BlueButton from "./components/BlueButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}  >
        
        {children}
         <nav>
           <NavElement icon={''} label="Adaence" />
           <NavElement icon={''} label="Accueil" />
           <NavElement icon={''} label="Je rends visite" />
           <NavElement icon={''} label="Guide du partage" />
           <NavElement icon={''} label="Devenir bénévole" />
           <BlueButton label="Faire un don" />  
         </nav>
      </body>
    </html>
  );
}
